### ISSUE TITLE
Unclear error code while testing

### ISSUE THREAD

**Issue by DCGenomics** [ncbi/pipelines#3]
(cwl) Bens-MBP:amr_finder benbusby$ ./amrfinder -p test_prot.fa
Required supplementary data not present, downloading via ftp.
  Fetching AMR.LIB...success!
  Fetching AMRProt...success!
  Fetching AMR_CDS...success!
  Fetching fam.tab...success!
  Fetching changes.txt...success!
['cwl-runner', '--user-space-docker-cmd', 'udocker', '/Users/benbusby/experiments/amr_finder/wf_amr_prot.cwl', '/var/folders/fd/2wlv763j4nd6kmpg89701kd80000gn/T/amr_params_rsfl0e.yaml']
Return code: 1
None

Docker is installed on this system but not udocker.

**Comment by slottad** [comment]
amrfinder only tries to run `udocker` when it can't find `docker` in the path.

What happens when you type `docker run hello-world` at the same prompt?

**Comment by clinardi** [comment]
Hi, I have the same problem and I was able to run "docker run hello-world" but I still have the following error.

cl:~/amr_finder$ ./amrfinder -p test_prot.fa -g test_prot.gff
Required supplementary data not present, downloading via ftp.
  Fetching AMR.LIB...success!
  Fetching AMRProt...success!
  Fetching AMR_CDS...success!
  Fetching fam.tab...success!
  Fetching changes.txt...success!
['cwl-runner', '/home/cl/amr_finder/wf_amr_prot.cwl', '/tmp/amr_params_deU2W4.yaml']
Return code: 1
None
cl:~/amr_finder$ ./amrfinder -p test_prot.fa -g test_prot.gff
['cwl-runner', '/home/cl/amr_finder/wf_amr_prot.cwl', '/tmp/amr_params_QsuswL.yaml']
Return code: 1
None

Do you know what might be the problem?

**Comment by slottad** [comment]
This doesn't look exactly like the same problem, since it is not trying to run udocker. Can you try running it again with the `-s` option and post the output?

**Comment by clinardi** [comment]
I get the following error

cl@bal2:~/amr_finder$ ./amrfinder -p test_prot.fa -g test_prot.gff -s
Traceback (most recent call last):
  File "/home/cl/miniconda2/bin/cwl-runner", line 7, in <module>
    from cwltool.main import main
  File "/home/cl/miniconda2/lib/python2.7/site-packages/cwltool/main.py", line 21, in <module>
    from schema_salad import validate
  File "/home/cl/miniconda2/lib/python2.7/site-packages/schema_salad/__init__.py", line 10, in <module>
    from .utils import onWindows
  File "/home/cl/miniconda2/lib/python2.7/site-packages/schema_salad/utils.py", line 8, in <module>
    from typing_extensions import Text  # pylint: disable=unused-import
  File "/home/cl/miniconda2/lib/python2.7/site-packages/typing_extensions.py", line 4, in <module>
    from typing import (
ImportError: cannot import name Counter
['cwl-runner', '/home/cl/amr_finder/wf_amr_prot.cwl', '/tmp/amr_params_nMQ1IA.yaml']
Return code: 1
None

**Comment by slottad** [comment]
There is something broken about your installation. Counter is part of typing, which extends collections, which is part of the standard package for python. Did you install this in a python virtualenv? Or forget to activate it?

I suggest creating a virtenv and reinstalling cwl.

**Comment by clinardi** [comment]
I get the following error when trying to make a virtualenv

cl@l:~$ virtualenv --python=python2 cwl
Running virtualenv with interpreter /home/cl/miniconda2/bin/python2
New python executable in /home/cl/cwl/bin/python2
Also creating executable in /home/cl/cwl/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/cl/cwl/bin/python2 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
ImportError: cannot import name main
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/cl/miniconda2/lib/python2.7/site-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/home/cl/miniconda2/lib/python2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/home/cl/miniconda2/lib/python2.7/site-packages/virtualenv.py", line 947, in create_environment
    download=download,
  File "/home/cl/miniconda2/lib/python2.7/site-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/cl/miniconda2/lib/python2.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/cl/cwl/bin/python2 - setuptools pip wheel failed with error code 1

**Comment by slottad** [comment]
What OS is this? You are using a version of python from your home directory, not the system one. You might try: `virtualenv --python=/usr/bin/python cwl`

**Comment by clinardi** [comment]
I was using ubuntu so I used the command

virtualenv -p /usr/bin/python cwl

It works perfectly now! Thank you so much for your help!

**Comment by clinardi** [comment]
Dear slottad,

I am now trying to run AMRFinder in a docker image. I have installed all the dependencies required but when testing it, the following error occurs.

(cwl) root@4003:/l3bioinfo/amr_finder# ./amrfinder -n test_dna.fa -s
Required supplementary data not present, downloading via ftp.
Fetching AMR.LIB...success!
Fetching AMRProt...success!
Fetching AMR_CDS...success!
Fetching fam.tab...success!
Fetching changes.txt...success!
/l3bioinfo/cwl/bin/cwl-runner 1.0.20181118133959
Resolved '/l3bioinfo/amr_finder/wf_amr_dna.cwl' to 'file:///l3bioinfo/amr_finder/wf_amr_dna.cwl'
[workflow ] start
[workflow ] starting step fasta_check
[step fasta_check] start
[job fasta_check] /tmp/tmprYJ1tL$ docker
run
-i
--volume=/tmp/tmprYJ1tL:/jgWagD:rw
--volume=/tmp/tmpwCW7AA:/tmp:rw
--volume=/l3bioinfo/amr_finder/test_dna.fa:/var/lib/cwl/stgc822ef1a-9c28-490a-953c-dd8bd4aa8ee2/test_dna.fa:ro
--workdir=/jgWagD
--read-only=true
--log-driver=none
--user=0:0
--rm
--env=TMPDIR=/tmp
--env=HOME=/jgWagD
ncbi/amr:18.06
fasta_check
/var/lib/cwl/stgc822ef1a-9c28-490a-953c-dd8bd4aa8ee2/test_dna.fa > /tmp/tmprYJ1tL/fasta_check.out
[job fasta_check] completed permanentFail
[step fasta_check] completed permanentFail
[workflow ] completed permanentFail
{
"fasta_check_out": {
"checksum": "sha1$ba94ee660aac5c886bfd4dff8db76dc196687907",
"basename": "fasta_check.out",
"location": "file:///l3bioinfo/amr_finder/fasta_check.out",
"path": "/l3bioinfo/amr_finder/fasta_check.out",
"class": "File",
"size": 213
},
"result": null
}
Final process status is permanentFail

ERROR
Reading line 0:

"common.cpp", line 645: i >= 0 && i <= 255
HOSTNAME: adadbe9f05a0
PWD: ?
Progam name: fasta_check
Command line: fasta_check /var/lib/cwl/stgc822ef1a-9c28-490a-953c-dd8bd4aa8ee2/test_dna.fa

What might be causing this problem?

I think it might have something to do with docker. The command I used to have docker inside the container is

cl@b:~$ docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v/usr/bin/docker:/usr/bin/docker amr-image:v2 bash

Thank you for your time and I look forward to your reply!
